# Generated by Django 3.1.4 on 2021-02-28 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='albums/', verbose_name='Обложка альбома')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата релиза')),
                ('count_of_plays', models.IntegerField(default=0, verbose_name='Прослушивания')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя артиста')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('img', models.ImageField(null=True, upload_to='artists/', verbose_name='Картинка артиста')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('release_date', models.DateField(null=True, verbose_name='Дата публикации')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='playlists/', verbose_name='Обложка плейлиста')),
                ('comment', models.TextField(null=True, verbose_name='Описание')),
                ('count_of_plays', models.IntegerField(default=0, verbose_name='Прослушивания')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.FileField(max_length=255, upload_to='songs_files/%Y/%m/%d/', verbose_name='Ссылка')),
                ('icon', models.ImageField(null=True, upload_to='songs/', verbose_name='Обложка песни')),
                ('duration', models.TimeField(verbose_name='Продолжительность')),
                ('category', models.CharField(max_length=255, verbose_name='Категория')),
                ('song_language', models.CharField(blank=True, max_length=50, null=True, verbose_name='Язык')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата релиза')),
                ('date_upload', models.DateField(auto_now_add=True, verbose_name='Дата загрузки на сайт')),
                ('count_of_plays', models.IntegerField(blank=True, default=0, verbose_name='Прослушивания')),
                ('album', models.ManyToManyField(to='main.Album', verbose_name='Альбом')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artist', verbose_name='Артист')),
                ('playlist', models.ManyToManyField(null=True, to='main.Playlist', verbose_name='Плейлист')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(to='main.Artist', verbose_name='Артист'),
        ),
    ]
