# Generated by Django 3.1.4 on 2021-03-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_song_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Артист', 'verbose_name_plural': 'Артисты'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['release_date', 'title'], 'verbose_name': 'Плейлист', 'verbose_name_plural': 'Плейлисты'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.AddField(
            model_name='artist',
            name='header_img',
            field=models.ImageField(null=True, upload_to='artists/headers/', verbose_name='Шапка артиста'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(null=True, upload_to='albums/', verbose_name='Обложка альбома'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(null=True, upload_to='playlists/', verbose_name='Обложка плейлиста'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(to='main.Artist', verbose_name='Артист'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='category',
        ),
        migrations.AlterField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(to='main.Playlist', verbose_name='Плейлист'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_language',
        ),
        migrations.AddField(
            model_name='song',
            name='category',
            field=models.ManyToManyField(to='main.Genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='song',
            name='song_language',
            field=models.ManyToManyField(to='main.Languages', verbose_name='Язык исполнения'),
        ),
    ]
