# Generated by Django 3.1.4 on 2021-04-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='my_music',
            field=models.ManyToManyField(to='main.Song', verbose_name='Моя музыка'),
        ),
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d', verbose_name='Картинка пользователя'),
        ),
    ]
