# Generated by Django 3.2.9 on 2022-07-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210406_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='my_artists',
            field=models.ManyToManyField(to='main.Artist', verbose_name='Мои исполнители'),
        ),
    ]
